### ISSUE TITLE
빌드 오류

### ISSUE THREAD

**Issue by jini5012** [monun/tap#20]
Task :api:compileKotlin FAILED
e: java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.pom.java.LanguageLevel
        at org.jetbrains.kotlin.com.intellij.core.CoreLanguageLevelProjectExtension.<init>(CoreLanguageLevelProjectExtension.java:26)
        at org.jetbrains.kotlin.com.intellij.core.JavaCoreProjectEnvironment.<init>(JavaCoreProjectEnvironment.java:42)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreProjectEnvironment.<init>(KotlinCoreProjectEnvironment.kt:26)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.<init>(KotlinCoreEnvironment.kt:118)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:420)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:226)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:371)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:105)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:249)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:38)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:80)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:92)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:602)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1644)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

gradlew clean jar를 치면 이렇게 나오는데 어떻게 해야 하나요?

**Comment by dolphin2410** [comment]
`legacy-jdk8` 브랜치와 `master` 브랜치에서 둘 다 테스트 해 본 결과 둘 다 정상적으로 작동했습니다. `git fetch`로 최신 버전을 유지하고, 그래도 안 되면 `Files > Invalidate Caches`를 사용해 보세요. (`:api:compileKotlin`를 보니 `legacy-jdk8` 또는 그 이하 버전 같네요)

**Comment by jini5012** [comment]
Could not find io.papermc.paper:paper:1.17.1-R0.1-SNAPSHOT.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/io/papermc/paper/paper/1.17.1-R0.1-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/io/papermc/paper/paper/1.17.1-R0.1-SNAPSHOT/paper-1.17.1-R0.1-SNAPSHOT.pom
  - https://papermc.io/repo/repository/maven-public/io/papermc/paper/paper/1.17.1-R0.1-SNAPSHOT/maven-metadata.xml
  - https://papermc.io/repo/repository/maven-public/io/papermc/paper/paper/1.17.1-R0.1-SNAPSHOT/paper-1.17.1-R0.1-SNAPSHOT.pom
  - https://libraries.minecraft.net/io/papermc/paper/paper/1.17.1-R0.1-SNAPSHOT/maven-metadata.xml
  - https://libraries.minecraft.net/io/papermc/paper/paper/1.17.1-R0.1-SNAPSHOT/paper-1.17.1-R0.1-SNAPSHOT.pom
  - file:/C:/Users/coding/.m2/repository/io/papermc/paper/paper/1.17.1-R0.1-SNAPSHOT/maven-metadata.xml
  - file:/C:/Users/coding/.m2/repository/io/papermc/paper/paper/1.17.1-R0.1-SNAPSHOT/paper-1.17.1-R0.1-SNAPSHOT.pom
Required by:
    project :tap-core:v1.17.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 근데 이건 뭐죠

**Comment by jini5012** [comment]
Could not resolve io.papermc.paper:paper:1.17-R0.1-SNAPSHOT.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

이건 또 뭐

**Comment by dolphin2410** [comment]
`./gradlew setupWorkspace`로 mavenLocal에 배포해야합니다.

**Comment by dolphin2410** [comment]
하다가 git 에러가 나면 `git submodules init`, `git submodules update`, `git gc`를 순서대로 해 보세요.

**Comment by xenon245** [comment]
./gradlew clean setupWorkspace 를 실행해도 안 고쳐질 겁니다. 저도 똑같이 떴었던 적이 있는데 인텔리제이를 지웠다 깔았더니 되더라고요. 인텔리제이를 로컬파일을 지운후 다시 깔아보세요.

**Comment by jini5012** [comment]
io.papermc.paper:paper:1.17.1-R0.1-SNAPSHOT.

이거 어디서 구해요?

**Comment by dolphin2410** [comment]
혹시 C:/Users/coding/.m2/repository 안에 io/papermc/paper/paper 디렉토리가 있나요?

**Comment by jini5012** [comment]
아 되네요 감사합니다

**Comment by jini5012** [comment]
어 잘못 눌렀다
