### ISSUE TITLE
lateinit property equipmentData has not been initialized

### ISSUE THREAD

**Issue by qogusdn1017** [monun/tap#35]
FakeEntity#updateEquippment
FakeEntity<Player>에게 적용하려고 하니 오류 발생
코드 필요하시면 말씀해주세요

```
[12:58:50] [Server thread/ERROR]: Uncaught exception in server thread
kotlin.UninitializedPropertyAccessException: lateinit property equipmentData has not been initialized
        at io.github.monun.tap.fake.internal.FakeEntityImpl.update$tap_core(FakeEntityImpl.kt:276) ~[?:?]
        at io.github.monun.tap.fake.internal.FakeEntityServerImpl.updateEntities(FakeEntityServerImpl.kt:172) ~[?:?]
        at io.github.monun.tap.fake.internal.FakeEntityServerImpl.update(FakeEntityServerImpl.kt:147) ~[?:?]
        at com.baehyeonwoo.notakomq.plugin.NotAKomqPluginMain$onEnable$2.invokeSuspend(NotAKomqPluginMain.kt:40) ~[NotAKomq.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-271]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by dolphin2410** [comment]
https://github.com/monun/tap/blob/9be0d48d1e31aafe22f906e0e7605bdd63a519d9/tap-core/src/main/kotlin/io/github/monun/tap/fake/internal/FakeEntityImpl.kt#L128

엔티티가 ArmorStand이어야합니다

**Comment by qogusdn1017** [comment]
절언
그럼 패킷서포트와 태스크 PPAP 하던지 Tap 소스를 수정하던지 하겠습니다
